---
title: "Recessions as Bread & Butter for Forecasters"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

cat("\014")  # clear console
rm(list=ls(all=TRUE))

```

```{r library, include=FALSE}
#### (0.1) BASICS: SET LIBRARIES
library(MASS)
library(utils)
library(zoo)
library(lubridate) # easy handling of dates
library(stringr) # for "str_extract"-function
library(forecast)
library(R.utils) # to use withTimeout
library(tidyverse)
library(dplyr)
library(tidyr)
library(readxl)
library(readr)
library(magrittr)
library(timetk)
```

```{r path, include=FALSE}
#path.main <- "/Users/danielwochner/Dropbox/ETH Zurich/Ph.D. Research/Research Projects/BB" # DSW Laptop
path      <-list()
path$main <- "C:/BBB/DW_BB4F/" # "C:/Users/BORISS/BBB/ZRH201812/DW_BB4F/"
path$data <- paste0( path$main, "DATA/")
path$code <- paste0( path$main, "CODE/")


```

```{r option, include=FALSE}
opt <- list()
opt$FRED_VNTG <- "2018-12"
opt$FRED_CSV  <- paste0( opt$FRED_VNTG,".csv" )

### set sample for the balanced data set
opt$date_beg = c(1960,1) %>% set_names( c("year","quarter") )
opt$date_end = c(2018,2) %>% set_names( c("year","quarter") )

opt$date_beg_text = sprintf( "%sQ%s", opt$date_beg["year"], opt$date_beg["quarter"] )
opt$date_end_text = sprintf( "%sQ%s", opt$date_end["year"], opt$date_end["quarter"] )

opt$date_beg_date = sprintf( "%s-%s-01", opt$date_beg["year"], opt$date_beg["quarter"] * 3 ) %>% as.Date
opt$date_end_date = sprintf( "%s-%s-01", opt$date_end["year"], opt$date_end["quarter"] * 3 ) %>% as.Date

opt$npca = 5
opt$nAR  = 4
#opt$FREDXLSX <- "2018-12.xlsx

```


```{r function, include=FALSE}
# PAPER: McCracken & Ng (2016) (in "TCODE" in Appendix) suggest 7 different variable transformations to make series stationary.
# I hereby follow their suggestions and apply these rules to apply these transformations to variables in FRED-MD and FRED-QD.
  


```


```{r data_init, include=FALSE}
# Read quarterly FRED database:
db_init <- tbl_df( read_csv( paste0( path$data, opt$FRED_CSV ) ) ); db_init 

### clean the database: set datestamp
db_ragged <- db_init %>% 
                filter( sasdate != "factors") %>% 
                filter( sasdate != "transform")

#db %>% .$sasdate %>% mdy

db_ragged %<>% mutate( date = mdy(sasdate) ) %>% 
        separate( ., sasdate, c("month","day","year"), sep = "/" ) %>%
        dplyr::select( -day ) %>%
        mutate( month = as.integer( month ) / 3, year = as.integer(year) ) %>%
        rename( quarter = month ) %>% 
        dplyr::select(date, year, quarter, everything() )

###### drop variables 
#( a ) that have NA in 1960Q1 
#( b ) that have NA in 2018Q3
#( c ) NONBORRES due to change in definition/structural change

list2remove_NA_BEG = db_ragged %>% 
                           filter( year == opt$date_beg["year"], quarter == opt$date_beg["quarter"] ) %>% 
                           select_if( function(x) is.na(x) ) %>% names

list2remove_NA_END = db_ragged %>% 
                           filter( year == opt$date_end["year"], quarter == opt$date_end["quarter"] ) %>% 
                           select_if( function(x) is.na(x) ) %>% names

list2remove = union( list2remove_NA_BEG, list2remove_NA_END ) %>% c( . , "NONBORRES" ) %>% unique

### create balanced data set
db = db_ragged %>% dplyr::select( -list2remove ) %>%
     filter( date >= opt$date_beg_date )  %>%
     filter( date <= opt$date_end_date ); dim( db )

names( db )

info.fctr <- db_init %>%  
           filter( sasdate == "factors") %>% 
           dplyr::select( -sasdate ) %>%
           dplyr::select( -list2remove ) 

list.fctr <- info.fctr %>% select_if( function(x) x == 1 )

info.trfm <- db_init  %>% 
           filter( sasdate == "transform") %>% 
           dplyr::select( -sasdate ) %>%
           dplyr::select( -list2remove ) 


### group variables by transformation
seq.trfm = info.trfm %>% t %>% as.vector %>% unique %>% sort

list.trfm = lapply( seq.trfm, function( i ) { 
  info.trfm[ which( info.trfm == i ) ] %>% names
}) %>% set_names( paste0( "trfm=", seq.trfm ) )


tsdb = db %>% ts( ., start = c( year( .$date[1] ), quarter( .$date[1]) ), frequency = 4 )

# Variable names with group name attached: for balanced db
# if: "2018-12.csv"  WHERE DID THE GROUP ASSIGNMENT COME FROM?!
info.group <- c( 1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	2,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	3,	4,	4,	4,	4,	4,	4,	4,	5,	5,	5,	5,	5,	5,	5,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	7,	7,	7,	7,	7,	7,	7,	7,	7,	7,	7,	7,	7,	8,	8,	8,	8,	8,	8,	8,	8,	8,	8,	8,	8,	8,	8,	9,	9,	9,	9,	9,	9,	9,	9,	9,	9,	9,	9,	10,	10,	10,	10,	10,	10,	10,	10,	13,	4,	4,	4,	11,	11,	11,	11,	11,	11,	12,	12,	1,	1,	14,	14,	2,	2,	2,	3,	3,	9,	9,	8,	8,	8,	8,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	6,	7,	9,	9,	9,	3,	3,	5,	5,	10,	8,	8,	4,	4,	4,	4,	13,	13,	6,	14,	14,	14,	14,	14,	14,	14,	14,	14,	14,	14,	13,	13,	13,	13) %>% 
  set_names( names(db_ragged)[ -which( names(db_ragged) %in% c( "date","quarter", "year" ) ) ] ) %>%
  .[ setdiff( names( . ), list2remove ) ] ### remove variables with NA either in the beg/end of the db_ragged

length( info.group )

seq.group = info.group %>% unique %>% sort

list.group = lapply( seq.group, function( i ) { 
  info.group[ which( info.group == i ) ] %>% names
}) %>% set_names( paste0( "group=", seq.group ) )

```

```{r data_trfm, include=FALSE}
###
### VARIABLE TRANSFORMATION (applied to raw data, incl. 1959)
###

### create transformed x matrix: 
### NB! trfm = 7 is not applied as "Original NONBORRES" looks odd

dbx = db %>% 
  mutate_at( .vars = list.trfm$`trfm=2`, .funs = funs(      .   -      lag( . , n = 1 )   ) ) %>%
  mutate_at( .vars = list.trfm$`trfm=5`, .funs = funs( log( . ) - log( lag( . , n = 1 ) ) ) ) %>%
  mutate_at( .vars = list.trfm$`trfm=6`, .funs = funs( log( . ) - log( lag( . , n = 1 ) ) -  
                                                     ( log( lag( . , n = 1 ) ) - log( lag( . , n = 2 ) ) ) ) ) 

### collect the dependent variable in one list for all h
list_dby = list()

list_dby$h1 = dbx

list_dby$h2 = db %>% 
  mutate_at( .vars = list.trfm$`trfm=2`, .funs = funs(        .   -      lag( . , n = 2 )   ) ) %>%
  mutate_at( .vars = list.trfm$`trfm=5`, .funs = funs(   log( . ) - log( lag( . , n = 2 ) ) ) ) %>%
  mutate_at( .vars = list.trfm$`trfm=6`, .funs = funs( ( log( . ) - log( lag( . , n = 2 ) ) ) / 2 - 
                                                       ( log( lag( . , n = 2 ) ) - log( lag( . , n = 3 ) ) ) ) ) 
list_dby$h4 = db %>% 
  mutate_at( .vars = list.trfm$`trfm=2`, .funs = funs(        .   -      lag( . , n = 4 )   ) ) %>%
  mutate_at( .vars = list.trfm$`trfm=5`, .funs = funs(   log( . ) - log( lag( . , n = 4 ) ) ) ) %>%
  mutate_at( .vars = list.trfm$`trfm=6`, .funs = funs( ( log( . ) - log( lag( . , n = 4 ) ) ) / 4 - 
                                                       ( log( lag( . , n = 4 ) ) - log( lag( . , n = 5 ) ) ) ) ) 

list_dby$h8 = db %>% 
  mutate_at( .vars = list.trfm$`trfm=2`, .funs = funs(        .   -      lag( . , n = 8 )   ) ) %>%
  mutate_at( .vars = list.trfm$`trfm=5`, .funs = funs(   log( . ) - log( lag( . , n = 8 ) ) ) ) %>%
  mutate_at( .vars = list.trfm$`trfm=6`, .funs = funs( ( log( . ) - log( lag( . , n = 8 ) ) ) / 8 - 
                                                       ( log( lag( . , n = 8 ) ) - log( lag( . , n = 9 ) ) ) ) ) 


plot( list_dby$h1$PCECTPI, type = "l",main = "PCECTPI" )
plot( list_dby$h2$PCECTPI, type = "l",main = "PCECTPI" )
plot( list_dby$h4$PCECTPI, type = "l",main = "PCECTPI" )
plot( list_dby$h8$PCECTPI, type = "l",main = "PCECTPI" )

dim( dbx )

```

```{r plot_GDPC1, include=T}
plot( list_dby$h1$GDPC1, type = "l",main = "GDPC1" )
plot( list_dby$h2$GDPC1, type = "l",main = "GDPC1" )
plot( list_dby$h4$GDPC1, type = "l",main = "GDPC1" )
plot( list_dby$h8$GDPC1, type = "l",main = "GDPC1" )
```

There are `r dim(dbx)[2]` columns in the balanced data panel. Observe that the total number of indicators is obtained by subtracting the number of columns with the timestamps: `r colnames(dbx) %>% head`. The balanced sample is `r opt$date_beg_text` - `r opt$date_end_text`. The common factors are extracted from `r length(list.fctr)` indicators.


```{r test, include=FALSE}
func_date2vec_m2q <- function( date ) return( c( year( date ), quarter( date ) ) )
func_vec2date_q2m <- function( vec  ) return( as.Date( sprintf( "%s-%s-01", vec["year"], vec["quarter"] * 3 ) ) )

func_doFcst = function( sz, ih, estn.end ){ 

#estn.end = c( 2016, 2 ) # c( 1984, 4 ),
#ih = 1
#sz = "GDPC1" #"PCDGx" #   

### set timing of the exercise
wndw = list()
wndw$h = ih
wndw$estn.end      = estn.end %>% set_names( c("year","quarter") )
wndw$estn.end.date = func_vec2date_q2m( wndw$estn.end )
wndw$fcst.tgt.date = wndw$estn.end.date + months( 3 * wndw$h )
wndw$fcst.tgt      = func_date2vec_m2q( wndw$fcst.tgt.date )


dby = list_dby[[ paste0("h",wndw$h)]] %>% select( date, sz )


### create AR terms of the dependent variable
dby_lag = list_dby[[ "h1" ]] %>% select( date, sz ) %>%
          mutate_at( .vars = sz, .funs = funs( `_hplus0` = lag( . , n = wndw$h     ) ) ) %>%
          mutate_at( .vars = sz, .funs = funs( `_hplus1` = lag( . , n = wndw$h + 1 ) ) ) %>%
          mutate_at( .vars = sz, .funs = funs( `_hplus2` = lag( . , n = wndw$h + 2 ) ) ) %>%
          mutate_at( .vars = sz, .funs = funs( `_hplus3` = lag( . , n = wndw$h + 3 ) ) ) %>%
          select( -sz ) %>%
          set_colnames( c("date", paste0( sz, "_", seq(wndw$h, wndw$h + 3 ) ) ) ) %>%
          select( date, paste0( sz, "_", seq(wndw$h, wndw$h + (opt$nAR - 1 ) ) ) )

dby_lag.beg.date = dby_lag %>% select( date ) %>% top_n( -1 ) %>% pull( 1 )
dby_lag.beg      = func_date2vec_m2q( dby_lag.beg.date )

tsy_lag.estn = dby_lag %>%
               filter( date <= wndw$estn.end.date ) %>%
               select( -date ) %>%
               ts( ., start = dby_lag.beg, frequency = 4 )

tsy_lag.fcst = dby_lag %>%
               filter( date == wndw$fcst.tgt.date ) %>%
               select( -date ) %>%
               ts( ., start = wndw$fcst.tgt, frequency = 4 )
### do PCA 

# remove sz from set of variables to do PCA
as.fctr = setdiff( colnames( list.fctr ), sz ) 

dbx.in = dbx %>% filter( date <= wndw$estn.end.date ) %>% na.omit 

### select the start date
dbx.in.beg.date = dbx.in %>% select( date ) %>% top_n( -1 ) %>% pull( 1 )
dbx.in.beg      = func_date2vec_m2q( dbx.in.beg.date )

### keep all extracted prcomp
pca.obj = dbx.in %>% 
          select( as.fctr ) %>% 
          prcomp( ., scale. = TRUE)

### keep first of eigenvalues
sdev = pca.obj$sdev %>% head

pca.slct = pca.obj$x[,1:opt$npca]

colnames( pca.slct )
### lag pca h-steps ahead: lost first h rows
tspca.estn_h = pca.slct %>% as.tibble %>%
               mutate_all( .funs = funs( lag( . , n = wndw$h ) ) ) %>% 
               set_names( paste0( colnames( . ),"_", wndw$h) ) %>% 
               ts( ., start = dbx.in.beg, frequency = 4 ) 

### set the last row in pca.slct as input for forecasting of the target quarter
tspca.fcst_h = pca.slct %>% as.tibble %>% tail(1) %>%
               set_names( paste0( colnames( . ),"_", wndw$h) ) %>% 
               ts( ., start = wndw$fcst.tgt, frequency = 4 )

### get dependent variable
tsy.estn.beg.date =  dby %>% select( date ) %>% top_n( -1 ) %>% pull( 1 )

tsy.estn = dby %>% 
           filter( date <= wndw$estn.end.date ) %>%
           select( -date ) %>%
           ts( ., start = func_date2vec_m2q( tsy.estn.beg.date ), frequency = 4 )

data.estn = cbind( tsy.estn, tspca.estn_h, tsy_lag.estn ) %>%
            magrittr::set_colnames( c( sz, colnames( tspca.estn_h ), colnames( tsy_lag.estn ) ) ) %>% 
            na.omit

formula.ardl = as.formula( paste( colnames(data.estn)[1], paste( colnames(data.estn)[-1], collapse = "+" ), sep = "~" ) )
formula.ar   = as.formula( paste( colnames(data.estn)[1], paste( colnames( tsy_lag.estn ), collapse = "+" ), sep = "~" ) )
formula.hm   = as.formula( paste( colnames(data.estn)[1], "~ 1" ) )


ols.ardl = lm( formula.ardl, data = data.estn )
ols.ar   = lm( formula.ar  , data = data.estn )
ols.hm   = lm( formula.hm , data = data.estn )

summary( ols.ardl ) 
summary( ols.ar ) 
summary( ols.hm ) 

ardl.fcst = predict( ols.ardl, cbind( tspca.fcst_h, tsy_lag.fcst ) %>% 
                      magrittr::set_colnames( c( colnames( tspca.estn_h ), colnames( tsy_lag.estn ) ) ) ) %>% 
            ts( ., start = wndw$fcst.tgt, frequency = 4 )

ar.fcst   = predict( ols.ar  , cbind( tsy_lag.fcst ) %>% 
                      magrittr::set_colnames( colnames( tsy_lag.estn ) ) ) %>% 
            ts( ., start = wndw$fcst.tgt, frequency = 4 )

hm.fcst   = ols.hm$coefficients %>% ts( ., start = wndw$fcst.tgt, frequency = 4 )

  
data.actl = data.estn[, sz ]
ols.ardl.fitd = ols.ardl$fitted.values %>% ts( ., start = start( data.estn ), frequency = 4 )
ols.ar.fitd   = ols.ar$fitted.values   %>% ts( ., start = start( data.estn ), frequency = 4 )
ols.hm.fitd   = ols.hm$fitted.values   %>% ts( ., start = start( data.estn ), frequency = 4 )


plot( data.actl, lwd = 2, main = paste( sz, ": h =", wndw$h ) ); 
lines( ols.ardl.fitd, lwd = 2, col = 2 )
lines( ols.ar.fitd  , lwd = 2, col = 4 )
lines( ols.hm.fitd  , lwd = 2, col = 3 )

list_ud = list( ardl.fcst = ardl.fcst, ar.fcst = ar.fcst, hm.fcst = hm.fcst )
return( list_ud )
}

#estn.end = c( 1984, 4 ); ih = 1; sz = "GDPC1" #"PCDGx" #  

list_estn.end = seq( as.Date( "1984-12-01"), as.Date( "2018-3-01"), by = "3 months" ) %>%
                lapply( ., function(x) func_date2vec_m2q( x ) )

estn.end = c( 1984, 4 ); ih = 1; sz = "GDPC1"
list.model.fcst = lapply( list_estn.end, function(date) func_doFcst( sz, ih, date ) )

### collect oos forecasts
ts.ardl.fcst = do.call( "rbind", lapply( list.model.fcst, `[[`, "ardl.fcst" ) ) %>% 
                                 ts( ., start = start(list.model.fcst[[1]]$`ardl.fcst`), frequency = 4 )

ts.ar.fcst   = do.call( "rbind", lapply( list.model.fcst, `[[`, "ar.fcst" ) ) %>% 
                                 ts( ., start = start(list.model.fcst[[1]]$`ar.fcst`), frequency = 4 )


ts.hm.fcst   = do.call( "rbind", lapply( list.model.fcst, `[[`, "hm.fcst" ) ) %>% 
                                 ts( ., start = start(list.model.fcst[[1]]$`hm.fcst`), frequency = 4 )

mts.fcst = cbind( ts.ardl.fcst, ts.ar.fcst, ts.hm.fcst )

ts.actl = list_dby[[ paste0("h",ih)]] %>% select( date, sz ) %>%
          filter( date >= func_vec2date_q2m( start( mts.fcst ) %>% set_names( c( "year","quarter" ) ) ) ) %>%
          filter( date <= func_vec2date_q2m( end(   mts.fcst ) %>% set_names( c( "year","quarter" ) ) ) ) %>%
          select( -date ) %>%
          ts( . , start = start( mts.fcst ), frequency = 4 )

cbind( ts.actl, mts.fcst ) %>% tk_tbl() %>% 
  mutate( erro.ardl = ts.actl - mts.fcst.ts.ardl.fcst ) %>% 
  mutate( erro.ar   = ts.actl - mts.fcst.ts.ar.fcst   ) %>% 
  mutate( erro.hm   = ts.actl - mts.fcst.ts.hm.fcst   ) %>% 
  mutate( ardl.rmsfe = sqrt( mean( ( erro.ardl )^2 ) ) ) %>%
  mutate( ar.rmsfe   = sqrt( mean( ( erro.ar   )^2 ) ) ) %>%
  mutate( hm.rmsfe   = sqrt( mean( ( erro.hm   )^2 ) ) )
 

```